const fs=require('fs'),path=require('path');
const sharp=require('/Users/m4/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/sharp');
const root='/Users/m4/project/rewords/猫窝乱斗/美术/试制/UI尺寸验证';
const dir=path.join(root,'v2-native-alpha');fs.mkdirSync(dir,{recursive:true});
(async()=>{
 const trimmed=await sharp(path.join(root,'button_source_v1.png')).trim({threshold:5}).png().toBuffer();
 const meta=await sharp(trimmed).metadata();
 const scaled=await sharp(trimmed).resize({height:104}).png().toBuffer();
 const m=await sharp(scaled).metadata();
 const cap=20;
 async function sized(w,h,file){
  const src=await sharp(scaled).resize({height:h}).png().toBuffer();const mm=await sharp(src).metadata();const c=Math.round(cap*h/104);
  const layers=[];
  for(const [sx,sw,dx,dw] of [[0,c,0,c],[c,mm.width-2*c,c,w-2*c],[mm.width-c,c,w-c,c]]){
   layers.push({input:await sharp(src).extract({left:sx,top:0,width:sw,height:h}).resize(dw,h).png().toBuffer(),left:dx,top:0});
  }
  await sharp({create:{width:w,height:h,channels:4,background:'#00000000'}}).composite(layers).png().toFile(path.join(dir,file));
 }
 await sized(496,104,'button_primary_2x_496x104.png');
 await sized(248,52,'sample_start_248x52.png');
 await sized(420,48,'sample_next_420x48.png');
 await sized(108,52,'sample_short_108x52.png');
 fs.writeFileSync(path.join(dir,'sample-metadata.json'),JSON.stringify({source:'../button_source_v1.png',sourceMethod:'built-in imagegen native alpha; Canva variant rejected for white artifacts',sourceDownloadedSize:[1939,811],trimmed:[meta.width,meta.height],master:[496,104],logical:[248,52],proposedUnityBorder:{left:20,right:20,top:12,bottom:12},pixelsPerUnit:200,canvasReferencePixelsPerUnit:100,notes:'Geometry packaging only: alpha trim, uniform height resampling, preserve end caps and adapt center width; no painted elements generated by code.'},null,2));
 const img=fs.readFileSync(path.join(dir,'button_primary_2x_496x104.png')).toString('base64');
 const html=`<!doctype html><meta charset="utf-8"><title>猫窝乱斗 · UI单件尺寸试制</title><style>*{box-sizing:border-box}body{background:#e9e3d5;color:#253b32;font-family:Arial,"PingFang SC",sans-serif;margin:32px}h1{font-size:24px}p{max-width:720px;line-height:1.7}section{background:#f6f3eb;padding:24px;margin:20px 0;max-width:780px;border-radius:12px}.row{display:flex;gap:24px;align-items:center;margin:22px 0}.skin{border-style:solid;border-width:6px 10px;border-image:url(data:image/png;base64,${img}) 12 20 fill stretch;background:transparent;color:#fff;font-size:16px;font-weight:700;cursor:pointer;display:inline-flex;align-items:center;justify-content:center;padding:0}.skin:active{filter:brightness(.82)}.pressed{filter:brightness(.82)}.disabled{filter:grayscale(1);opacity:.55;cursor:default}.label{font-size:14px;color:#566257}code{font-size:13px}small{display:block;margin-top:8px}</style><h1>一张无字底图，保留程序布局</h1><p>这是单件皮肤试制预览，不是 Unity 实机截图。逻辑尺寸按 540×960 基准，文字独立叠加。按钮范围不随按下状态变化。</p><section><div class=row><button class=skin style="width:248px;height:52px">开始守梦</button><span class=label>248 × 52 · 正常</span></div><div class=row><button class="skin pressed" style="width:248px;height:52px">开始守梦</button><span class=label>248 × 52 · 按下（程序调暗）</span></div><div class=row><button disabled class="skin disabled" style="width:248px;height:52px">开始守梦</button><span class=label>248 × 52 · 禁用（程序状态）</span></div></section><section><div class=row><button class=skin style="width:420px;height:48px">下一夜</button><span class=label>420 × 48</span></div><div class=row><button class=skin style="width:108px;height:52px">免费刷新</button><span class=label>108 × 52 · 仅验证窄尺寸；正式次级按钮另用弱色</span></div><small>九宫格：左右边角保持尺寸，只适配中间区域。纹理最终参数仍需单件 Unity 接入审查。</small></section>`;
 fs.writeFileSync(path.join(dir,'preview.html'),html);
 console.log(JSON.stringify({trimmed:[meta.width,meta.height],master:[496,104],outputs:dir}));
})();
