(() => {
 const root=document.getElementById('hub-study');
 const demo={page:'home',selected:1,cleared:0,coins:120,level:1,signed:false,supplied:false,task:false};
 let returnFocus=null;
 const asset=n=>`assets/${n}.png`;
 root.innerHTML=`<div class="hub-intro"><div><h2>今晚，从家里出发</h2><p>主界面 → 爬楼 → 布置 → 战斗 → 回家培养</p></div><span>交互草案 · 养成与奖励数值仅示意</span></div><div id="hub-toast" role="status" aria-live="polite"></div><div class="hub-workspace"><div class="hub-device"><div class="hub-screen"><header class="hub-top"><button class="hub-avatar" data-action="profile" aria-label="玩家信息">猫</button><div><strong>守梦小屋</strong><small>第一章 · 夜色初临</small></div><button class="hub-currency" data-action="supply" aria-label="培养币补给">✦ <b id="hub-coins">120</b><small>培养币 ＋</small></button><button class="hub-gear" data-action="settings" aria-label="设置">☰</button></header><div id="hub-content"></div><nav class="hub-bottom" aria-label="主要功能"><button data-page="cats"><span>♧</span>猫咪</button><button data-page="home"><span>⌂</span>小屋</button><button data-page="tower"><span>▤</span>爬楼</button><button data-page="items"><span>◇</span>图鉴</button></nav></div></div><aside class="hub-notes"><span class="hub-kicker">本轮一起看什么</span><h2>有自己的猫，<br>也有下一层期待。</h2><p>小屋用来收集、培养和领取补给。楼层展示当前目标，准备页才开始购买和摆放。</p><ol><li>点猫咪，试试培养和资源消耗。</li><li>点签到、任务，领取一次奖励。</li><li>进入爬楼，上下滑动并点选楼层。</li><li>挑战第一层，接到已有布置与战斗。</li></ol><div class="hub-note-card"><b>演示边界</b><p>第一层可实际战斗；后续楼层先看目标与奖励。培养只演示局外交互，暂不改变战斗数值。刷新页面会重置。</p></div><button class="hub-plain" data-action="reset">重置本轮演示 ↺</button></aside></div><dialog id="hub-dialog" aria-labelledby="hub-dialog-title"><div class="hub-modal-head"><span>守梦小屋</span><button id="hub-dialog-close" aria-label="关闭弹窗">×</button></div><div id="hub-dialog-body"></div></dialog>`;
 const content=document.getElementById('hub-content'),modal=document.getElementById('hub-dialog');
 const floorNames=['床底的手','倒走闹钟','衣柜长影','走廊低语','门后的影子','长夜守门人'];
 const enemies=['enemy_under_bed','enemy_clock','enemy_wardrobe'];
 function showStudy(name){document.body.dataset.study=name;document.querySelectorAll('[data-study-link]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.studyLink===name)));if(name==='hub')draw();window.scrollTo({top:0,behavior:'instant'});}
 document.querySelectorAll('[data-study-link]').forEach(b=>b.onclick=()=>showStudy(b.dataset.studyLink));
 function toast(t){const el=document.getElementById('hub-toast');el.textContent=t;clearTimeout(toast.timeout);toast.timeout=setTimeout(()=>el.textContent='',2600);}
 function close(){modal.close();const target=returnFocus?.isConnected?returnFocus:(returnFocus?.dataset.action?root.querySelector('[data-action="'+returnFocus.dataset.action+'"]'):null);target?.focus();}
 function open(title,body,buttons=[]){if(!modal.open)returnFocus=document.activeElement;document.getElementById('hub-dialog-body').innerHTML=`<h2 id="hub-dialog-title">${title}</h2>${body}<div class="hub-modal-actions"></div>`;const box=modal.querySelector('.hub-modal-actions');buttons.forEach(([label,fn,disabled=false])=>{const b=document.createElement('button');b.className='hub-primary';b.textContent=label;b.disabled=disabled;b.onclick=fn;box.append(b);});if(!modal.open)modal.showModal();else (box.querySelector('button:not(:disabled)')||document.getElementById('hub-dialog-close')).focus();}
 document.getElementById('hub-dialog-close').onclick=close;modal.addEventListener('cancel',e=>{e.preventDefault();close();});
 function draw(){document.getElementById('hub-coins').textContent=demo.coins;document.querySelectorAll('[data-page]').forEach(b=>b.setAttribute('aria-current',b.dataset.page===demo.page?'page':'false'));
 if(demo.page==='home')content.innerHTML=`<section class="hub-home"><div class="hub-home-title"><small>灯亮着，猫就在这里。</small><h2>今晚也要睡个好觉</h2></div><div class="hub-side"><button data-action="signin"><span>☀</span>签到${demo.signed?' ✓':''}</button><button data-action="tasks"><span>☷</span>任务${demo.cleared&&!demo.task?' •':''}</button><button data-action="supply"><span>✦</span>补给</button></div><button class="hub-cat-scene" data-action="cat" aria-label="查看面条猫"><img class="hub-nest" src="${asset('nest_fabric_v1')}" alt="布艺猫窝"><img class="hub-resident" src="${asset('cat_noodle_pose0')}" alt="面条猫"><span>面条 <b>Lv.${demo.level}</b> ♡</span></button><div class="hub-home-next"><small>下一站 · 第一章</small><strong>第 ${demo.cleared+1} 层 · ${floorNames[demo.cleared]}</strong><button class="hub-primary" data-page="tower">${demo.cleared?'继续向上':'开始爬楼'} <span>→</span></button></div></section>`;
 if(demo.page==='tower')drawTower();
 if(demo.page==='cats')content.innerHTML=`<section class="hub-collection"><small class="hub-kicker">一起守梦的伙伴</small><h2>我的猫咪 <small>1 / 3</small></h2><p>认识它的本领，再试一种新搭配。</p><button class="hub-cat-card" data-action="cat"><img src="${asset('cat_noodle_pose0')}" alt="面条"><div><b>面条 · Lv.${demo.level}</b><span>连击猫 · 喜欢玩具</span><small>查看与培养 →</small></div></button><button class="hub-cat-card muted" data-action="lockedcat"><img src="${asset('cat_hammer_pose0')}" alt="锤锤"><div><b>锤锤</b><span>重击猫 · 尚未结识</span><small>查看获取方向 →</small></div></button><div class="hub-soft-note">培养币用于小屋成长，和挑战中购买用品的金币分开。</div></section>`;
 if(demo.page==='items')content.innerHTML=`<section class="hub-collection"><small class="hub-kicker">把喜欢的东西放在身边</small><h2>用品图鉴</h2><p>查看占格与联动；实际购买在准备页。</p>${[['item_feather','逗猫棒','横向 2 格 · 贴着面条，出爪更快'],['item_mouse','发条鼠','用品效果待接入本轮示意'],['item_cushion','软垫','用品效果待接入本轮示意']].map(([img,name,copy],i)=>`<button class="hub-item-card" data-item="${i}"><img src="${asset(img)}" alt=""><div><b>${name}</b><span>${copy}</span></div></button>`).join('')}</section>`;
 }
 function drawTower(){const n=demo.selected,current=demo.cleared+1;content.innerHTML=`<section class="hub-tower"><header><small>第一章 · 夜色初临</small><h2>梦里的旧楼 <span>${demo.cleared} / 6 层</span></h2></header><div class="hub-floors" aria-label="楼层列表，上下滑动查看"><div class="hub-rooftop">☾ 越过长夜，天就亮了</div>${[6,5,4,3,2,1].map(f=>`<button class="hub-floor ${f===n?'selected':''} ${f>current?'locked':''} ${f<=demo.cleared?'cleared':''}" data-floor="${f}" aria-pressed="${f===n}"><span class="hub-floor-number">${String(f).padStart(2,'0')}<small>层</small></span><span class="hub-window">${f===6?'☾':f<=demo.cleared?'✓':f===current?'♧':'·'}</span><span class="hub-floor-label"><b>${floorNames[f-1]}</b><small>${f<=demo.cleared?'已守住':f===current?'当前挑战':'通过前一层解锁'}</small></span><span>${f===6?'♛':f===current?'←':'⌑'}</span></button>`).join('')}<div class="hub-ground">从这里，一层一层守住美梦</div></div><div class="hub-floor-detail"><div><img src="${asset(enemies[Math.min(n-1,2)])}" alt="梦魇示意"><div><small>第 ${n} 层${n>3?' · 敌人形象暂借用':''}</small><b>${floorNames[n-1]}</b><span>首通 ✦ ${n===6?100:30} 培养币</span></div><button class="hub-info" data-action="milestone" aria-label="查看章节奖励">♧</button></div><button class="hub-primary" data-action="challenge" ${n!==1||demo.cleared?'disabled':''}>${n<=demo.cleared?'本层已通关':n>current?'先通过前一层':n>1?'后续战斗待接入':'进入第 1 层 · 布置猫窝 →'}</button></div></section>`;requestAnimationFrame(()=>{const box=content.querySelector('.hub-floors'),selected=box.querySelector('.selected');box.scrollTop=selected.offsetTop-box.offsetTop-box.clientHeight/2+selected.clientHeight/2;});}
 function cat(){open('面条 · 连击猫',`<img class="hub-modal-cat" src="${asset('cat_noodle_pose0')}" alt="面条"><p>喜欢玩具，擅长连续出爪。把逗猫棒贴在它身边，可以更快攻击。</p><div class="hub-level">Lv.${demo.level} <span>→</span> Lv.${demo.level+1}</div><p class="hub-small">培养演示：花费 40 培养币提升 1 级。此处暂不改变战斗数值。</p>`,[['培养 · 40 培养币',()=>{if(demo.coins<40)return;demo.coins-=40;demo.level++;draw();cat();},demo.coins<40]]);}
 const actions={cat,signin(){open('每天回来，摸摸猫',`<p>今天的见面礼：30 培养币。</p><div class="hub-sign-days">${[1,2,3,4,5,6,7].map(n=>`<span class="${n===1?'today':''}">${n}<small>${n===1&&demo.signed?'已领':'日'}</small></span>`).join('')}</div><p class="hub-small">本轮只演示第 1 天，不随真实日期累计。</p>`,[[demo.signed?'今日已领取':'领取今日奖励',()=>{if(demo.signed)return;demo.signed=true;demo.coins+=30;close();draw();toast('签到成功 · +30 培养币');},demo.signed]]);},tasks(){open('今晚的小目标',`<div class="hub-task-row"><div><b>守住第 1 层</b><p>进度 ${demo.cleared?1:0} / 1</p></div><b>✦ 50</b></div><p>回到小屋，给一起守梦的猫咪一点奖励。</p>`,[[demo.task?'奖励已领取':demo.cleared?'领取 · 50 培养币':'先去挑战第 1 层',()=>{if(!demo.cleared){close();demo.page='tower';draw();return;}if(demo.task)return;demo.task=true;demo.coins+=50;close();draw();toast('任务完成 · +50 培养币');},demo.task]]);},supply(){open('小屋补给',`<p>额外获得 40 培养币，给猫咪再升一级。</p><p class="hub-small">模拟激励视频：点击下方按钮代表完整看完，关闭弹窗不发奖。本轮限领一次。</p>`,[[demo.supplied?'本轮已领取':'模拟看完视频 · +40',()=>{if(demo.supplied)return;demo.supplied=true;demo.coins+=40;close();draw();toast('补给到账 · +40 培养币');},demo.supplied]]);},lockedcat(){open('还没遇见锤锤',`<img class="hub-modal-cat" src="${asset('cat_hammer_pose0')}" alt="锤锤"><p>重击方向的伙伴。后续可用章节推进解锁，具体条件尚待设计。</p>`,[['去看看楼层',()=>{close();demo.page='tower';draw();}]]);},milestone(){open('这一章的目标',`<p>守住第 6 层，领取章节奖励。</p><div class="hub-level">✦ 100 培养币</div><p class="hub-small">当前 ${demo.cleared} / 6 层。章节奖励与后续战斗尚未接入，不能提前领取。</p>`);},profile(){open('守梦人',`<p>已结识 1 只猫咪<br>已守住 ${demo.cleared} 层<br>面条 Lv.${demo.level}</p>`);},settings(){open('关于这版示意',`<p>主界面、爬楼和局外培养是本轮交互草案。资源只在当前页面保留，刷新后重置。</p>`,[['重新开始演示',()=>location.reload()]]);},reset(){location.reload();},challenge(){if(demo.selected!==1||demo.cleared)return;showStudy('combat');setView(state.phase==='prep'?'prep':'battle');document.getElementById('live-study').scrollIntoView({behavior:'instant',block:'start'});}};
 root.addEventListener('click',e=>{const b=e.target.closest('button');if(!b||b.disabled)return;if(b.dataset.page){demo.page=b.dataset.page;draw();}else if(b.dataset.floor){demo.selected=Number(b.dataset.floor);draw();}else if(b.dataset.action){actions[b.dataset.action]?.();}else if(b.dataset.item){const i=Number(b.dataset.item);open(['逗猫棒','发条鼠','软垫'][i],`<p>${i===0?'横向占 2 格；与面条上下左右贴边后，出爪更快。进入挑战后，在床边小铺购买，再从待放区拖入猫窝。':'本轮先展示图鉴入口，具体效果请以后续配置为准。'}</p>`);}});
 const finish=document.createElement('button');finish.className='paper';finish.textContent='领取首通奖励 · 返回楼层';finish.onclick=()=>{if(!demo.cleared){demo.cleared=1;demo.coins+=30;}finish.textContent='返回楼层';demo.page='tower';demo.selected=2;showStudy('hub');toast('第 1 层已守住 · 首通奖励仅领取一次');};document.getElementById('result').append(finish);
 draw();
})();
